In [1]:
import numpy as np
import cv2

In [2]:
img=cv2.imread(r"D:\FaceRecognition_Flask-main\FaceRecognition_Flask-main\facerecognition_flask\New folder\data\friends.jpg")

In [3]:
cv2.imshow("original",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
#casecade classfier
harr=cv2.CascadeClassifier(r"D:\FaceRecognition_Flask-main\FaceRecognition_Flask-main\facerecognition_flask\haarcascade_frontalface_default.xml")

In [17]:
image=img.copy()

#step-1: convert image to grayscale
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#step2: apply grayscale image to casecade classifier

face_rect=harr.detectMultiScale(gray,1.3,5)
# step 3:draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('detected face',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
print(face_rect)

[[255  88  97  97]
 [128 106  96  96]
 [405  92  96  96]]


## Real TIme face detectionusing opencv

In [26]:
cap=cv2.VideoCapture(r"D:\FaceRecognition_Flask-main\FaceRecognition_Flask-main\facerecognition_flask\New folder\data\video.mp4")
while True:
    ret,frame=cap.read()
    if ret==False:
        break
    image=frame.copy()

    #step-1: convert image to grayscale
    gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    #step2: apply grayscale image to casecade classifier
    
    face_rect=harr.detectMultiScale(gray,1.3,5)
    # step 3:draw bounding box
    for x,y,w,h in face_rect:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.imshow('face detection',image)
    if cv2.waitKey(1)==27:
        break
cap.release()
cv2.destroyAllWindows()